---

- include_vars: vars_RedHat_CentOS.yml
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- include_vars: vars_SUSE_openSUSE.yml
  when: 'ansible_os_family == "Suse" or ansible_os_family == "openSUSE Leap"'

- name: "Install package(s) {{ iscsiadmin_package }}"
  yum:
    name: "{{ iscsiadmin_package }}"
    state: 'installed'

- name: "Start and enable {{ iscsiadmin_service }} service"
  service:
    name: "{{ iscsiadmin_service }}"
    enabled: true
    state: 'started'

- name: Collect facts about installed iSCSI initiator
  iscsiadm_facts:

- name: Setup iSCSI Initiator name
  lineinfile:
    dest: '/etc/iscsi/initiatorname.iscsi'
    regexp: '^InitiatorName='
    line: "InitiatorName={{ custom_iscsi_initiator_name is defined|ternary(custom_iscsi_initiator_name,iscsi_initiator_name) }}"
    create: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: restart service

- meta: flush_handlers

- name: Connect to iSCSI target
  include_tasks: connect_to_target.yml
  when: iscsi_target_ip is defined
